language: php

php:
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit